#!/bin/sh
terraform init -backend=false
terraform fmt
CHANGED=$(git diff --cached --name-only)
terraform validate
x=$?
echo $x
if [ $x -ne 0 ]
then echo terraform files not valid
exit $x
fi
git add $CHANGED
