on:
  push:
    branches:    
      - master
name: tf-lint docker build
jobs:
  tf-lintIsMaster:
    name: tf-lint is master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: tf-lint action
      uses: docker://cdssnc/touched-github-action:latest
      with:
        args: tf-lint/**
  
