name: CI

on: 
  pull_request:
    branches:
      - master

jobs:
  tf_fmt:
    name: format
    runs-on: ubuntu-latest
    steps:
    - name: Terraform format
      uses: cds-snc/github-actions/tf-lint@v1.0.0
