name: CI

on: 
  pull_request:
    branches:
      - master

jobs:
  tf_fmt:
    name: Validate Validate
    runs-on: ubuntu-latest
    steps:
    - name: Run tflint with reviewdog
      uses: reviewdog/action-tflint@v1.0.0
