name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run tflint with reviewdog
      run:  |
        wget https://github.com/wata727/tflint/releases/download/v0.12.1/tflint_darwin_amd64.zip
        unzip tflint_darwin_amd64.zip
        mkdir -p /usr/local/tflint/bin
        export PATH=/usr/local/tflint/bin:$PATH
        install tflint /usr/local/tflint/bin
        tflint -v
