name: reviewdog
on: [pull_request]
jobs:
  tflint:
    name: runner / tflint
    runs-on: ubuntu-latest

    steps:
      - name: Run tflint with reviewdog
        uses: reviewdog/action-tflint@v1.0.0
      
